on: issue_comment
name: Issue Comments
jobs:
  check_comments:
    name: Check comments for /test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Check for Command
        id: command
        uses: BALABHASKARARAO/gh-actions-merge-command@v1
        #uses: Goobles/gh-actions-merge-command@v1
        with:
          allow_ff: false
          command: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #command: test
      #- name: Act on the command
       # run: |
       #   echo "The command was '${{ steps.command.outputs.command-name }}' with arguments '${{ steps.command.outputs.command-arguments }}'"
       #   echo "HI"
